version: '3.8'

services:
  # Portainer Instace
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /P4RAD0X/containers/portainer/:/data
    networks:
      - default

# Networks
networks:
  default:
    driver: bridge



