[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"

[git_branch]
symbol = "ðŸ“¦ "

[directory]
truncation_length = 1
style = "blue bold"

[username]
style_user = "yellow bold"
disabled = true

[hostname]
disabled = true

[cmd_duration]
min_time = 500
format = "took [$duration](yellow) "